apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: zigante/delivery-simulator-backend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: backend-volume
              mountPath: /home/node/app/.env
              subPath: .env
      volumes:
        - name: backend-volume
          configMap:
            name: backend-configs
            items:
              - key: env
                path: .env
