version: '3'

services:
  app:
    container_name: backend
    build: .
    entrypoint: ./scripts/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:4.4.4
    restart: always
    volumes:
      - ./data/dbdata:/data/db
      - ./data/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nest

  mongodb-frontend:
    container_name: mongodb-frontend
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
