apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-configs
data:
  env: |
    KAFKA_BOOTSTRAP_SERVERS=pkc-43n10.us-central1.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=simulator
    KAFKA_PRODUCE_TOPIC=route.new-position
    KAFKA_READ_TOPIC=route.new-direction
    CONFLUENT_SECURITY_PROTOCOL="SASL_SSL"
    CONFLUENT_SASL_MECHANISMS="PLAIN"
    CONFLUENT_CLUSTER_API_KEY=""
    CONFLUENT_CLUSTER_API_SECRET=""
